version: "3.8"

networks:
  apigateway_system_network:
    external: true

services:
  authentication_server:
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5000:5000"
    env_file:
      - ./.env.prod
    hostname:
      authentication_server
    networks:
      - apigateway_system_network
  
  authentication_db:
    env_file:
      - ./.env.prod
    hostname:
      authentication_db
    networks:
      - apigateway_system_network