version: "3.8"
services:
  authentication_db:
    image: postgres:latest
    container_name: authentication_postgres
    restart: always
    env_file:
      - ./.env.dev


  authentication_server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    depends_on:
      - authentication_db
    volumes:
    - ./coverage_reports:/work/coverage_reports
    